
DROP TABLE IF EXISTS CLIENT;
CREATE TABLE IF NOT EXISTS CLIENT (
  CLIENT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  SCHOOL_ID MEDIUMINT(9) NOT NULL,
  CLIENT_CODE VARCHAR(10),
  NAME VARCHAR(75) NOT NULL,
  CONTACT_NAME VARCHAR(250) NULL DEFAULT NULL,
  ADDRESS VARCHAR(75) NULL DEFAULT NULL,
  COUNTRY_ID BIGINT(20),
  CITY VARCHAR(150) NULL DEFAULT NULL,
  PHONE VARCHAR(12) NULL DEFAULT NULL,
  FAX VARCHAR(12) NULL DEFAULT NULL,
  EMAIL VARCHAR(30) NULL DEFAULT NULL,
  WEBSITE VARCHAR(100) NULL DEFAULT NULL,
  CREATE_DATE TIMESTAMP NOT NULL  ,
  MOD_DATE TIMESTAMP NOT NULL ,
  MOD_BY BIGINT(20) NOT NULL,
  PRIMARY KEY (CLIENT_ID),
  CONSTRAINT FK_CLIENT_11 FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (COUNTRY_ID));

-- -----------------------------------------------------
-- TABLE PROJECT
-- -----------------------------------------------------
DROP TABLE IF EXISTS PROJECT ;

CREATE TABLE IF NOT EXISTS PROJECT (
  PROJECT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  SCHOOL_ID MEDIUMINT(9) NOT NULL,
  PROJECT_CODE VARCHAR(10),
   COUNTRY_ID BIGINT(20),
  CITY VARCHAR(150) NULL DEFAULT NULL,
  CLIENT_ID BIGINT(20) NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  ESTIMATED_START_DATE DATE,
  ESTIMATED_END_DATE DATE,
  ACTUAL_START_DATE DATE,
  ACTUAL_END_DATE DATE,
  BUDGET DECIMAL(10,2) NOT NULL  DEFAULT 0,
  BILL_HOURS DECIMAL(7,2) NOT NULL  DEFAULT 0,
  NONBILL_HOURS DECIMAL(7,2) NOT NULL  DEFAULT 0,
  STATUS SMALLINT(6) NULL DEFAULT '0' COMMENT '0-SALES, 1- STARTED, 3-ON HOLD, 4-CANCELLED, 99-COMPLETED',
  CREATE_DATE TIMESTAMP NOT NULL  ,
  MOD_DATE TIMESTAMP NOT NULL ,
  MOD_BY BIGINT(20) NOT NULL,
  PRIMARY KEY (PROJECT_ID),
 CONSTRAINT FK_PROJECT_1 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
 CONSTRAINT FK_PROJECT_2 FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (COUNTRY_ID)
);

-- -----------------------------------------------------
-- TABLE SUB_PROJECT
-- -----------------------------------------------------
DROP TABLE IF EXISTS SUB_PROJECT ;

CREATE TABLE IF NOT EXISTS SUB_PROJECT (
  SUB_PROJECT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  SCHOOL_ID MEDIUMINT(9) NOT NULL,
  SUB_PROJECT_CODE VARCHAR(10) NOT NULL,
  PROJECT_ID BIGINT(20) NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  ESTIMATED_START_DATE DATE,
  ESTIMATED_END_DATE DATE,
  ACTUAL_START_DATE DATE,
  ACTUAL_END_DATE DATE,
  BUDGET DECIMAL(10,2) NOT NULL DEFAULT 0,
  BILL_HOURS DECIMAL(7,2) NOT NULL  DEFAULT 0,
  NONBILL_HOURS DECIMAL(7,2) NOT NULL  DEFAULT 0,
  STATUS SMALLINT(6) NULL DEFAULT '0' COMMENT '0-SALES, 1- STARTED, 3-ON HOLD, 4-CANCELLED, 99-COMPLETED',
  CREATE_DATE TIMESTAMP NOT NULL   ,
  MOD_DATE TIMESTAMP NOT NULL ,
  MOD_BY BIGINT(20) NOT NULL,
  PRIMARY KEY (SUB_PROJECT_ID),
  CONSTRAINT FK_SUB_PROJECT_1 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
  );

  DROP TABLE IF EXISTS USER_PROJECT ;
CREATE TABLE IF NOT EXISTS USER_PROJECT (
  USER_PROJECT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  SCHOOL_ID MEDIUMINT(9) NOT NULL,
  PROJECT_ID BIGINT(20) NOT NULL,
  USER_ID BIGINT(20) NOT NULL,
  POSITION_ID MEDIUMINT(9) NOT NULL,
  HOURLY_RATE DECIMAL (8,2),
  CREATE_DATE TIMESTAMP NOT NULL  ,
  MOD_DATE TIMESTAMP NOT NULL ,
  MOD_BY BIGINT(20) NOT NULL,
  PRIMARY KEY (USER_PROJECT_ID),
  CONSTRAINT FK_PROJECT_USER_1
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID),
  CONSTRAINT FK_PROJECT_USER_2
    FOREIGN KEY (PROJECT_ID)
    REFERENCES PROJECT (PROJECT_ID),
	  CONSTRAINT FK_PROJECT_USER_3
    FOREIGN KEY (POSITION_ID)
    REFERENCES POSITION (POSITION_ID));

DROP TABLE IF EXISTS TIME_ENTRY ;
CREATE TABLE IF NOT EXISTS TIME_ENTRY (
	TIME_ENTRY_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	SCHOOL_ID MEDIUMINT(9) NOT NULL,
    SUB_PROJECT_ID BIGINT(20) NOT NULL,
	CLIENT_CODE VARCHAR(10) NOT NULL,
	PROJECT_CODE VARCHAR(10) NOT NULL,
	SUB_PROJECT_CODE VARCHAR(10) NOT NULL,
	BILL TINYINT NOT NULL DEFAULT 0 COMMENT '0-NON BILL  1-BILL',
	WORK_DATE DATE NOT NULL,
    HOURS DECIMAL (4,2),
	DESCRIPTION VARCHAR(1000) NOT NULL,
    USER_ID BIGINT(20) NOT NULL,
    FIRST_DAY_WEEK DATE NOT NULL,
    WEEK_NBR MEDIUMINT(9) NOT NULL,
    LINE_NBR MEDIUMINT(9) NOT NULL,
    LOCKED TINYINT NOT NULL DEFAULT 0,
	CREATE_DATE TIMESTAMP NOT NULL ,
	MOD_DATE TIMESTAMP NOT NULL ,
	MOD_BY BIGINT(20) NOT NULL,
	PRIMARY KEY (TIME_ENTRY_ID),
	CONSTRAINT FK_TIME_ENTRY_USER_1
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID),
	  CONSTRAINT FK_TIME_ENTRY_USER_2
    FOREIGN KEY (SUB_PROJECT_ID)
    REFERENCES SUB_PROJECT (SUB_PROJECT_ID));
