 INSERT INTO MARK(SCHOOL_ID, EXAM_ID,ENROLLMENT_ID,MARK,GRADE_ID,CREATE_DATE,MOD_DATE,APPROVED_BY)
 SELECT SCHOOL_ID, EXAM_ID,ENROLLMENT_ID,MARK,GRADE_ID,CREATE_DATE,MOD_DATE,APPROVED_BY FROM MARK;
 
  INSERT INTO MARK(SCHOOL_ID, EXAM_ID,ENROLLMENT_ID,MARK,GRADE_ID,CREATE_DATE,MOD_DATE,MOD_BY,APPROVED_BY)
 SELECT M.SCHOOL_ID, M.EXAM_ID,1,ROUND(RAND()*C.MAX_MARK,2),GRADE_ID,M.CREATE_DATE,M.MOD_DATE,1,M.APPROVED_BY FROM MARK M, EXAM E, COURSE C
 WHERE M.EXAM_ID=E.EXAM_ID
 AND C.COURSE_ID=E.COURSE_ID
 AND M.ENROLLMENT_ID=2;
 
 
  
   INSERT INTO MARK(SCHOOL_ID, EXAM_ID,ENROLLMENT_ID,MARK,GRADE_ID,CREATE_DATE,MOD_DATE,MOD_BY,APPROVED_BY)
  SELECT M.SCHOOL_ID, M.EXAM_ID+58,ENROLLMENT_ID,LEAST(C.MAX_MARK,MARK*1.4),GRADE_ID,M.CREATE_DATE,M.MOD_DATE,1,M.APPROVED_BY FROM MARK M, EXAM E, COURSE C
  WHERE M.EXAM_ID=E.EXAM_ID
  AND C.COURSE_ID=E.COURSE_ID
  AND M.EXAM_ID<59
  
 AND M.ENROLLMENT_ID=2;
 
 UPDATE 
 
 
 INSERT INTO EXAM (EXAM_ID,SCHOOL_ID,NAME,EXAM_DATE,EXAM_TYPE_ID, EVALUATION_TYPE, PUBLISH_MARKS, 
  COURSE_ID,TERM_ID, MAX_MARK, RATIO, SCHOOLYEAR_ID, CREATE_DATE,  MOD_DATE, MOD_BY)
  SELECT EXAM_ID+58,SCHOOL_ID,NAME,EXAM_DATE,1, EVALUATION_TYPE, PUBLISH_MARKS, 
  COURSE_ID,TERM_ID, MAX_MARK, RATIO, SCHOOLYEAR_ID, CREATE_DATE,  MOD_DATE, MOD_BY
  FROM EXAM;
  
  UPDATE EXAM SET EVALUATION_TYPE=0, EXAM_TYPE_ID = 1 WHERE 
  EXAM_ID IN (1,30,2,33,12,55,3,35,4,37,5,39,14,41,6,43,7,45,8,47,9,49,10,51,11,53)